SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `member_addresses`;
TRUNCATE TABLE `members`;

-- ----------------------------
-- 开始初始化数据
-- ----------------------------

INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (1, '13503804580', '苗苗', '苗苗', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (1, 1, '苗苗', '13503804580', '市区', '宝龙龙邸 4号楼1单元1202', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (2, '13938768398', '张娜', '张娜', '', 6, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (2, 2, '张娜', '13938768398', '市区', '东区/新二街宝龙世家西门往北50米中国体育彩票', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (3, '150 3662 4101', '李佳丽', '李佳丽', '', 6, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (3, 3, '李佳丽', '150 3662 4101', '市区', '宝龙葛记红焖放前台', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (4, '15225935226', '郝郝', '郝郝', '', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (4, 4, '郝郝', '15225935226', '市区', '枫景上东-6号楼2单元2105', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (5, '15516527581', '宋雨薇', '宋雨薇', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (5, 5, '宋雨薇', '15516527581', '市区', '枫景上东-11号楼2单元404', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (6, '无', '慧子', '慧子', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (6, 6, '慧子', '无', '市区', '诚城紫钰北区-52号楼2单元 2202', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (7, '13598617970', '悦已', '悦已', '', 6, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (7, 7, '悦已', '13598617970', '市区', '常青藤17号楼二单元1501', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (8, '15637399816', '洋洋', '洋洋', '', 6, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (8, 8, '洋洋', '15637399816', '市区', '周六送：紫钰口才星主播放前台
周五送豫飞·金色城邦7号楼3004', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (9, '15736990666', '焦磊', '焦磊', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (9, 9, '焦磊', '15736990666', '市区', '碧桂园时代城-6号楼5楼502室', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (10, '17739191399', '丰萍', '丰萍', '', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (10, 10, '丰萍', '17739191399', '市区', '泰安路新二街交叉口南 30米，DJI倚天摄影器材', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (11, '13789073701', '天天', '天天', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (11, 11, '天天', '13789073701', '市区', '跨境贸易大厦(可以放大厅前台)', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (12, '18637352697', '中中', '中中', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (12, 12, '中中', '18637352697', '市区', '嘉亿互联网大厦二楼 前台', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (13, '18738372222', '周周', '周周', '', 6, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (13, 13, '周周', '18738372222', '市区', '世纪村15号楼2单元3楼东户', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (14, '159-0389-9656', '林辉', '林辉', '', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (14, 14, '林辉', '159-0389-9656', '市区', '伟业中央公园16号楼一单元1502', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (15, '13837375666', '申奥', '申奥', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (15, 15, '申奥', '13837375666', '市区', '和谐城小区-9号楼2单元801', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (16, '13072662392', '方悦', '方悦', '', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (16, 16, '方悦', '13072662392', '市区', '牧野区逸品紫晶2号楼3单元703', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (17, '13503735127', '樊肖捷', '樊肖捷', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (17, 17, '樊肖捷', '13503735127', '市区', '阳光365小区-5号楼一单元701', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (18, '18530710880', '珍珠', '珍珠', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (18, 18, '珍珠', '18530710880', '市区', '只有周二-周六送
竹馨居2号楼2单元1803，直接挂门把手就行
中心医院门诊大楼3楼A区/', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (19, '15903875314', '羊', '羊', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (19, 19, '羊', '15903875314', '市区', '康桥美庭-4号楼二单元二楼东', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (20, '19337380888', '周周', '周周', '', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (20, 20, '周周', '19337380888', '市区', '正商城二期 19号楼2302', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (21, '13523230531', '张超', '张超', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (21, 21, '张超', '13523230531', '市区', '周六 到 华恩城西区13号楼一单元9楼西户
周一-周五 到 第三附属医院内科楼13楼护士站', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (22, '18532297750', '李嘉伟', '李嘉伟', '不要芝麻', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (22, 22, '李嘉伟', '18532297750', '市区', '牧野区荣校路-龙湖景庭-2号楼1单元605放到门口水桶上', '不要芝麻', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (23, '166 3736 5665', '云上', '云上', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (23, 23, '云上', '166 3736 5665', '市区', '中建海德壹号9号楼1单元809', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (24, '13569854800', '王晖', '王晖', '', 6, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (24, 24, '王晖', '13569854800', '市区', '中建海德壹号4号楼1101', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (25, '13839055526', '李海玲', '李海玲', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (25, 25, '李海玲', '13839055526', '市区', '金辰国际6号楼三单元', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (26, '17371250315', '一只三文鱼', '一只三文鱼', '不要洋葱葱姜蒜', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (26, 26, '一只三文鱼', '17371250315', '市区', '牧野区-二十二所第一生活区-2号楼1单元3楼西', '不要洋葱葱姜蒜', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (27, '15603739778', '路路', '路路', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (27, 27, '路路', '15603739778', '市区', '郊委路-太阳城一期-3号楼201-放家门口', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (28, '16627755424', '泡泡', '泡泡', '不打电话', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (28, 28, '泡泡', '16627755424', '市区', '都市名城1号楼1单元11楼1106', '不打电话', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (29, '13598680803', '韩啊园', '韩啊园', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (29, 29, '韩啊园', '13598680803', '市区', '北辰悦府-1号楼2单元10楼1001门口有个凳子', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (30, '13781939428', '白玉', '白玉', '', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (30, 30, '白玉', '13781939428', '市区', '牧野区-河师大家属院-20号楼6单元3楼西户', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (31, '15225980158', '孟1', '孟1', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (31, 31, '孟1', '15225980158', '市区', '达安花园3号楼2单元11楼西户 放家门口 不用敲门打电话', '', 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (32, 31, '孟2', '15225980158', '市区', '达安花园3号楼2单元11楼西户 放家门口 不用敲门打电话', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (32, '13333732120', '李飞凡', '李飞凡', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (33, 32, '李飞凡', '13333732120', '市区', '溥诚花园一号楼二单元放楼下拍照', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (33, '13837369696', '陈女士', '陈女士', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (34, 33, '陈女士', '13837369696', '市区', '红旗小区北区-2号楼2单元3楼东', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (34, '15893806517', '陈晨', '陈晨', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (35, 34, '陈晨', '15893806517', '市区', '红旗小区南区-8号楼-2单元-502', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (35, '18437919028', '周末', '周末', '', 6, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (36, 35, '周末', '18437919028', '市区', '华兰大道牧野大道交叉口五号食堂4楼外卖架', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (36, '13837343744', '赵琰', '赵琰', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (37, 36, '赵琰', '13837343744', '市区', '国悦城悦府壹号院4号楼一单元602', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (37, '18337311022', '王晓庆', '王晓庆', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (38, 37, '王晓庆', '18337311022', '市区', '高新区政府行政服务中心-华兰大道470号', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (38, '18337373251', '琼琼', '琼琼', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (39, 38, '琼琼', '18337373251', '市区', '五一路-上海城东区-C4号楼-1单元903', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (39, '18737306642', '文女士', '文女士', '', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (40, 39, '文女士', '18737306642', '市区', '火电厂家属院3号楼2单元1楼东户', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (40, '13303733442', '贾瑞', '贾瑞', '别打电话，放门口', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (41, 40, '贾瑞', '13303733442', '市区', '和平路纺织路交叉口隆基新谊城8号楼4单元1501', '别打电话，放门口', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (41, '18638315659', '张云1', '张云1', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (42, 41, '张云1', '18638315659', '市区', '新飞大道道-清路新乡融诚信息咨询中心前台', '', 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (43, 41, '张云2', '18638315659', '市区', '新飞大道道-清路新乡融诚信息咨询中心前台', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (42, '18236141334', '刘思雨', '刘思雨', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (44, 42, '刘思雨', '18236141334', '市区', '道清路-温泉花园小区-696号', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (43, '18337325613', '李瑞', '李瑞', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (45, 43, '李瑞', '18337325613', '市区', '道清路-青青家园-7号楼-西单元-4楼西户', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (44, '13273714230', '马晓楠', '马晓楠', '', 5, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (46, 44, '马晓楠', '13273714230', '市区', '大桥云锦府19号楼1单元2201', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (45, '13598660312', '静静', '静静', '', 3, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (47, 45, '静静', '13598660312', '市区', '宸·瑜伽教练培训学院一楼前台/胖东来德里克斯对', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (46, '18790785678', '李琛', '李琛', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (48, 46, '李琛', '18790785678', '市区', '忆通壹世界从南门进2号楼2单元2902', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (47, '13103737399', '高力', '高力', '', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (49, 47, '高力', '13103737399', '市区', '忆通壹世界从北门进19号楼1单元1502', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (48, '1590305000', '张媛媛', '张媛媛', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (50, 48, '张媛媛', '1590305000', '市区', '东关大街董欣护肤品/地图搜索大东街社区卫生服务站', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (49, '15137386331', '柠檬糖', '柠檬糖', '自取', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (51, 49, '柠檬糖', '15137386331', '市区', '东大街蚝市自提', '自取', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (50, '13673664084', '李伟', '李伟', '找跑腿', 23, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (52, 50, '李伟', '13673664084', '市区', '东大街蚝市自提  / 跑腿送九鼎美庐1号楼二单元903室', '找跑腿', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (51, '16638392000', '王丽娜', '王丽娜', '周六开始配送', 6, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (53, 51, '王丽娜', '16638392000', '市区', '葛记烩面（劳动桥店）', '周六开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (52, '15036611288', '张萍', '张萍', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (54, 52, '张萍', '15036611288', '市区', '恒基时代广场，1号楼1单元1902挂门上就可以了', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (53, '15517331110', '刘静懿', '刘静懿', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (55, 53, '刘静懿', '15517331110', '市区', '粮食局家属院6号楼三单元三楼左手边 到了打电话下来拿 / 公安局交警支队', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (54, '17630171678', '弓长', '弓长', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (56, 54, '弓长', '17630171678', '市区', '星海假日王府一期1号楼2单元403室', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (55, '18837311116', '张1', '张1', '', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (57, 55, '张1', '18837311116', '市区', '星海假日王府一期3号楼2203', '', 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (58, 55, '张2', '18837311116', '市区', '星海假日王府一期3号楼2203', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (56, '15670510280', '菲菲', '菲菲', '不要香菜，不要菠菜', 5, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (59, 56, '菲菲', '15670510280', '市区', '星海假期王府二期1号楼1单元404', '不要香菜，不要菠菜', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (57, '13460477488', '郭敏', '郭敏', '', 6, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (60, 57, '郭敏', '13460477488', '市区', '三胖二楼奶糖派', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (58, '15537355888', '陈书文1', '陈书文1', '', 5, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (61, 58, '陈书文1', '15537355888', '市区', '在南环，客户每天都说来自提还跑腿配送', '', 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (62, 58, '陈书文2', '15537355888', '市区', '在南环，客户每天都说来自提还跑腿配送', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (59, '17516019965', '叶子萌', '叶子萌', '', 0, '次卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (63, 59, '叶子萌', '17516019965', '市区', '店内自取', '', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (60, '18790545856', '李亚', '李亚', '自取', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (64, 60, '李亚', '18790545856', '市区', '东大街蚝市自提', '自取', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (61, '18637308802', '·', '·', '4月20日开始配送', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (65, 61, '·', '18637308802', '市区', '新生巷与西大街美食街交叉口征兵办(胡同最里面)', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (62, '17337337775', '焦点', '焦点', '4月20日开始配送', 6, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (66, 62, '焦点', '17337337775', '市区', '派克公馆D座2111', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (63, '15136760777', '李洋1', '李洋1', '4月20日开始配送', 5, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (67, 63, '李洋1', '15136760777', '市区', '平原路老四中对面极客通讯', '4月20日开始配送', 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (68, 63, '李洋2', '15136760777', '市区', '平原路老四中对面极客通讯', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (64, '13323738251', '牛菁菁', '牛菁菁', '4月20日开始配送', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (69, 64, '牛菁菁', '13323738251', '市区', '石牌坊/红旗区东街市场监管所', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (65, '18695922228', '33', '33', '4月20日开始配送', 0, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (70, 65, '33', '18695922228', '市区', '宝龙商场澳门街那个4号门古茗旁边/快到跟打电话', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (66, '13072666882', '李女士', '李女士', '4月20日开始配送', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (71, 66, '李女士', '13072666882', '市区', '新飞大道与友谊路交叉口-中国平安财产保险股份有限公司', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (67, '15837393243', '刘', '刘', '4月20日开始配送', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (72, 67, '刘', '15837393243', '市区', '宏力大道与和平大道交叉口中国银行', '4月20日开始配送', 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (73, 67, '刘', '15837393243', '市区', '宏力大道与和平大道交叉口中国银行', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (68, '15090361727', '11', '11', '4月20日开始配送', 0, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (74, 68, '11', '15090361727', '市区', '新乡市第二人民医院5号楼5楼icu', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (69, '13653907075', '王晴', '王晴', '4月20日开始配送', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (75, 69, '王晴', '13653907075', '市区', '光彩大市场南面过河，道河世家小区，银行', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (70, '18611288062', '赵火火', '赵火火', '4月20日开始配送', 0, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (76, 70, '赵火火', '18611288062', '市区', '荷塘月色假日酒店-20楼2012', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (71, '13837399234', '舞魅', '舞魅', '4月20日开始配送', 0, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (77, 71, '舞魅', '13837399234', '市区', '精神病院家属院24号楼2单元6楼西户', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (72, '15690794444', '毛艳飞', '毛艳飞', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (78, 72, '毛艳飞', '15690794444', '市区', '紫郡18号楼二单元 1603室', '4月20日开始配送', 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (79, 9, '焦磊', '15736990666', '市区', '碧桂园时代城-6号楼5楼502室', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (73, '19121270632', '李卓儒', '李卓儒', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (80, 73, '李卓儒', '19121270632', '市区', '靖业公元国际 30楼-不从米诺斯上/从西边电梯上30楼', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (74, '15690796622', '姚帅星', '姚帅星', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (81, 74, '姚帅星', '15690796622', '市区', '伟业中央公园16号楼2单元1901', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (75, '13683738639', '杨蓉', '杨蓉', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (82, 75, '杨蓉', '13683738639', '市区', '新乡医学院南校区-南门口 打电话', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (76, '18303612777', '王纯', '王纯', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (83, 76, '王纯', '18303612777', '市区', '云锦府7号楼2单元601', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (77, '18838766185', '大橘子', '大橘子', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (84, 77, '大橘子', '18838766185', '市区', '胜利中街与人民中路交叉口东南60米 中国建设银行4楼', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (78, '18613730000', '苑', '苑', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (85, 78, '苑', '18613730000', '市区', '荣校东路竹馨居11号楼一单元401', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (79, '13937338601', '岁月静好', '岁月静好', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (86, 79, '岁月静好', '13937338601', '市区', '星海假日王府2期5号楼2单元21楼2103', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (80, '18623737961', '王大喜', '王大喜', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (87, 80, '王大喜', '18623737961', '市区', '新五街东方家园2号楼2单元7楼东', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (81, '15736969016', '于悦', '于悦', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (88, 81, '于悦', '15736969016', '市区', '牧野区-河师大家属院-27号楼2单元402', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (82, '13525000736', '杨颂', '杨颂', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (89, 82, '杨颂', '13525000736', '市区', '前进路金色城邦一号楼一单元2503', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (83, '18838706190', '石炎', '石炎', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (90, 83, '石炎', '18838706190', '市区', '健康路与劳动路交叉口西北角三石町寿司', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (84, '15565722060', '洋洋', '洋洋', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (91, 84, '洋洋', '15565722060', '市区', '新二街牧野花园西门38-2-1102', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (85, '15565213209', '宋佳依', '宋佳依', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (92, 85, '宋佳依', '15565213209', '市区', '东升小区二号楼四单元5楼南户', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (86, '18637361993', '郑雪雅', '郑雪雅', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (93, 86, '郑雪雅', '18637361993', '市区', '卫滨区人民路健民二巷东方国际小区3号楼603', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (87, '15083103158', '洪女士', '洪女士', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (94, 87, '洪女士', '15083103158', '市区', '友谊路建业壹号城邦三期23号楼1单元2103', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (88, '15670503558', '妍姝', '妍姝', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (95, 88, '妍姝', '15670503558', '市区', '东郡府苑东苑，37号楼东单元三楼西户', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (89, '17651958426', '潘豆儿', '潘豆儿', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (96, 89, '潘豆儿', '17651958426', '市区', '红旗区华兰大道河南科技学院西门口-大学城口', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (90, '15537316006', '王女士', '王女士', '4月20日开始配送', 24, '月卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (97, 90, '王女士', '15537316006', '市区', '伟业公园9号楼5单元1001室', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (91, '13781991718', '王慧', '王慧', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (98, 91, '王慧', '13781991718', '市区', '红旗区劳动路十中巷芳草苑2号楼1单元1号', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (92, '15903889925', '宁宁', '宁宁', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (99, 92, '宁宁', '15903889925', '市区', '互联网大厦2606', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (93, '18237366612', '王雯雯', '王雯雯', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (100, 93, '王雯雯', '18237366612', '市区', '东明大道与向阳路交叉口东500米路北建业世和府 2-1-902', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (94, '13460245124', '孟女士', '孟女士', '周5，周6请假/4月20日开始配送', 6, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (101, 94, '孟女士', '13460245124', '市区', '绿营花园第1期-5号楼-部队东门小窗台', '周5，周6请假/4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (95, '18838753293', '王璐', '王璐', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (102, 95, '王璐', '18838753293', '市区', '学院路东风路交叉路口阳光体育（旁边小门上二楼）', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (96, '13937365881', '代女士', '代女士', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (103, 96, '代女士', '13937365881', '市区', '纺织路祥瑞花园4号楼2单元3楼东户', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (97, '18695939222', '牛臻', '牛臻', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (104, 97, '牛臻', '18695939222', '市区', '门店自提', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (98, '15660557288', '梦琦', '梦琦', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (105, 98, '梦琦', '15660557288', '市区', '火电厂家属院9号楼2单元4层', '4月20日开始配送', 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (106, 95, '王璐', '18838753293', '市区', '学院路东风路交叉路口阳光体育（旁边小门上二楼）', '4月20日开始配送', 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (107, 96, '代女士', '13937365881', '市区', '纺织路祥瑞花园4号楼2单元3楼东户', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (99, '15637358860', '郁先生', '郁先生', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (108, 99, '郁先生', '15637358860', '市区', '南区/劳动路华悦家园一号楼一单元三楼东', '4月20日开始配送', 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (109, 97, '牛臻', '18695939222', '市区', '门店自提', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (100, '18317576999', '李琳', '李琳', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (110, 100, '李琳', '18317576999', '市区', '世纪村八栋2单元 603', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (101, '13781932085', '婧婧', '婧婧', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (111, 101, '婧婧', '13781932085', '市区', '宝龙国际社区8号楼2单元1307', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (102, '16691810509', '刘璟辰', '刘璟辰', '4月20日开始配送', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (112, 102, '刘璟辰', '16691810509', '市区', '竹馨居-13号楼1403', '4月20日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (103, '18439082533', '靳豆豆', '靳豆豆', '周5，周6请假，4月20配送', 5, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (113, 103, '靳豆豆', '18439082533', '市区', '盛大凯旋城西门13号楼1205', '周5，周6请假，4月20配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (104, '18837338833', '成光泽', '成光泽', '周5，周6请假，4月20配送', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (114, 104, '成光泽', '18837338833', '市区', '牧野区-金辰国际-7号楼2单元东电梯1701
外卖放到七号楼二单元东边电梯拍照就行', '周5，周6请假，4月20配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (105, '19561960029', '方', '方', '下周一4.20号开始送', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (115, 105, '方', '19561960029', '市区', '第二人民医院南侧外贸家属院北楼三单元三楼东', '下周一4.20号开始送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (106, '15286910838', '张女士', '张女士', '周5，周6请假，4月20配送', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (116, 106, '张女士', '15286910838', '市区', '诚诚紫钰北区-58号楼2单元 302', '周5，周6请假，4月20配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (107, '13839065606', '市政府', '市政府', '需要加热
周5，周6请假，4月20配送', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (117, 107, '市政府', '13839065606', '市区', '市政府门口传达室，拍照发群', '需要加热
周5，周6请假，4月20配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (108, '18810891478', '黄芒果', '黄芒果', '请假4月21号开始送', 5, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (118, 108, '黄芒果', '18810891478', '市区', '牧野花园 28号楼2单元1202', '请假4月21号开始送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (109, '15137335868', '程芳', '程芳', '周五周六不送，4月20日不送
4月21日开始配送', 0, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (119, 109, '程芳', '15137335868', '市区', '红旗区向阳路松江帕提欧小区7号楼2单元1101', '周五周六不送，4月20日不送
4月21日开始配送', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (110, '18838769517', '任如意', '任如意', '不吃葱 不吃香菜 不吃蒜。
暂时不送转了2月钱', 48, '月卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (120, 110, '任如意', '18838769517', '市区', '河南省新乡市红旗区新飞建业府6号楼1单元301', '不吃葱 不吃香菜 不吃蒜。
暂时不送转了2月钱', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (111, '18537301666', '崔崔', '崔崔', '另行通知', 23, '月卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (121, 111, '崔崔', '18537301666', '市区', '宝龙世家4号楼二单元 3202', '另行通知', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (112, '13623904044', '王海燕', '王海燕', '另行通知', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (122, 112, '王海燕', '13623904044', '市区', '回来再报地址', '另行通知', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (113, '18238659505', '郭', '郭', '另行通知', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (123, 113, '郭', '18238659505', '市区', '卫滨区解放大道紫台一品一期八号楼10楼A', '另行通知', 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (124, 28, '泡泡', '16627755424', '市区', '都市名城1号楼1单元11楼1106', '另行通知', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (114, '15103739799', '郭宁', '郭宁', '另行通知', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (125, 114, '郭宁', '15103739799', '市区', '新乡三胖西侧内部路2栋公寓旁验货办公室', '另行通知', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (115, '17630170801', '小宁', '小宁', '另行通知', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (126, 115, '小宁', '17630170801', '市区', '发现生活咖啡馆（文化街店）放前台即可', '另行通知', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (116, '15727396999', '珠珠1', '珠珠1', '另行通知', 5, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (127, 116, '珠珠1', '15727396999', '市区', '丰华街建业森林半岛三号楼17楼东户', '另行通知', 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (128, 116, '珠珠2', '15727396999', '市区', '丰华街建业森林半岛三号楼17楼东户', '另行通知', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (117, '18603733011', '邹志毅', '邹志毅', '另行通知', 6, '周卡', 1, 0);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (129, 117, '邹志毅', '18603733011', '市区', '人民路新中大道交叉口星海如意大厦 404 室', '另行通知', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (118, '18238778808', '梅子', '梅子', '另行通知', 6, '周卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (130, 118, '梅子', '18238778808', '市区', '大桥云锦府3 号楼2单元902', '另行通知', 1);
INSERT INTO `members` (`id`, `phone`, `name`, `wechat_name`, `remarks`, `balance`, `plan_type`, `is_active`, `is_leaved_tomorrow`) VALUES (119, '15516623633', '樊洁', '樊洁', '5月6日', 24, '月卡', 1, 1);
INSERT INTO `member_addresses` (`id`, `member_id`, `contact_name`, `contact_phone`, `area`, `detail_address`, `remarks`, `is_default`) VALUES (131, 119, '樊洁', '15516623633', '市区', '健康路29号院五栋3单元一东', '5月6日', 1);

SET FOREIGN_KEY_CHECKS = 1;